FROM node:lts-alpine AS builder

# Ensure npm is available
RUN apk add --no-cache npm

WORKDIR /app

COPY package*.json ./

RUN npm ci --legacy-peer-deps # legacy because of liquid glass package

COPY . .

RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

